baseURL = 'https://grimmlabs.org/'
languageCode = 'en-us'
title = 'Grimm Labs'

# Taxonomies: This enables the "authors" feature
[taxonomies]
  team = "team"
  tag = "tags"
  category = "categories"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

# Menu Configuration


[[menu.main]]
  name = 'Webring'
  url = 'https://webring.grimmlabs.org'
  weight = 5

[[menu.main]]
  name = 'Discord'
  url = 'https://discord.grimmlabs.org'
  weight = 6
